"""Git manager for leetcode-sync.

Handles git operations safely:
- Never force pushes
- Never resets the repository
- Never overwrites unrelated files
- Warns before staging unrelated modifications
"""

from __future__ import annotations

import logging
import subprocess
from pathlib import Path

logger = logging.getLogger(__name__)


class GitError(Exception):
    """Raised when a Git operation fails."""


class GitManager:
    """Manages Git operations for the leetcode-sync repository."""

    def __init__(self, repo_path: Path | None = None) -> None:
        """Initialize the Git manager.

        Args:
            repo_path: Path to the Git repository. If None, uses cwd.
        """
        self.repo_path = repo_path or Path.cwd()

    def _run_git(
        self, *args: str, check: bool = True
    ) -> subprocess.CompletedProcess[str]:
        """Run a git command.

        Args:
            *args: Git command arguments.
            check: Whether to raise on non-zero exit.

        Returns:
            CompletedProcess result.

        Raises:
            GitError: If the command fails.
        """
        try:
            result = subprocess.run(
                ["git", *args],
                cwd=self.repo_path,
                capture_output=True,
                text=True,
                check=check,
            )
            return result
        except FileNotFoundError as e:
            raise GitError(
                "Git is not installed or not in PATH."
            ) from e
        except subprocess.CalledProcessError as e:
            raise GitError(
                f"Git command failed: git {' '.join(args)}\n{e.stderr}"
            ) from e

    def is_git_repo(self) -> bool:
        """Check if the current directory is a Git repository."""
        try:
            self._run_git("rev-parse", "--git-dir")
            return True
        except GitError:
            return False

    def has_remote(self) -> bool:
        """Check if a remote is configured."""
        result = self._run_git("remote", check=False)
        return bool(result.stdout.strip())

    def get_current_branch(self) -> str:
        """Get the current branch name."""
        result = self._run_git("branch", "--show-current")
        return result.stdout.strip()

    def get_status(self) -> str:
        """Get the git status."""
        result = self._run_git("status", "--short")
        return result.stdout.strip()

    def get_changed_files(self) -> list[str]:
        """Get list of changed files."""
        result = self._run_git(
            "diff", "--name-only", check=False
        )
        unstaged = (
            result.stdout.strip().split("\n")
            if result.stdout.strip()
            else []
        )

        result = self._run_git(
            "diff", "--cached", "--name-only", check=False
        )
        staged = (
            result.stdout.strip().split("\n")
            if result.stdout.strip()
            else []
        )

        result = self._run_git(
            "ls-files", "--others",
            "--exclude-standard", check=False,
        )
        untracked = (
            result.stdout.strip().split("\n")
            if result.stdout.strip()
            else []
        )

        all_files = set(unstaged + staged + untracked)
        all_files.discard("")
        return sorted(all_files)

    def stage_files(self, files: list[str]) -> None:
        """Stage specific files."""
        if not files:
            return
        self._run_git("add", *files)

    def has_uncommitted_changes(self) -> bool:
        """Check if there are uncommitted changes."""
        result = self._run_git("status", "--porcelain")
        return bool(result.stdout.strip())

    def commit(self, message: str) -> bool:
        """Create a commit.

        Args:
            message: Commit message.

        Returns:
            True if commit was created, False if nothing to commit.
        """
        if not self.has_uncommitted_changes():
            return False

        self._run_git("commit", "-m", message)
        return True

    def push(self) -> None:
        """Push the current branch to origin.

        Never force pushes.
        """
        branch = self.get_current_branch()
        self._run_git("push", "origin", branch)

    def init_repo(self, path: Path | None = None) -> None:
        """Initialize a new Git repository.

        Args:
            path: Path to initialize. If None, uses repo_path.
        """
        target = path or self.repo_path
        self._run_git("init", str(target))
        self.repo_path = target

    def stage_generated_files(self, files: list[str]) -> list[str]:
        """Stage only files that were generated by leetcode-sync.

        Warns about unrelated modifications.
        Returns list of files that were actually staged.
        """
        if not files:
            return []

        staged_files = list(files)
        self.stage_files(staged_files)
        return staged_files
